const champTable = {
  'alistar': { 'championName': '亞歷斯塔', 'championKey': 'alistar', 'idx': 4 },
  'aphelios': { 'championName': '亞菲利歐', 'championKey': 'aphelios', 'idx': 8 },
  'ezreal': { 'championName': '伊澤瑞爾', 'championKey': 'ezreal', 'idx': 28 },
  'irelia': { 'championName': '伊瑞莉雅', 'championKey': 'irelia', 'idx': 42 },
  'illaoi': { 'championName': '伊羅旖', 'championKey': 'illaoi', 'idx': 41 },
  'evelynn': { 'championName': '伊芙琳', 'championKey': 'evelynn', 'idx': 27 },
  'elise': { 'championName': '伊莉絲', 'championKey': 'elise', 'idx': 26 },
  'kled': { 'championName': '克雷德', 'championKey': 'kled', 'idx': 61 },
  'kalista': { 'championName': '克黎思妲', 'championKey': 'kalista', 'idx': 51 },
  'kayle': { 'championName': '凱爾', 'championKey': 'kayle', 'idx': 56 },
  'caitlyn': { 'championName': '凱特琳', 'championKey': 'caitlyn', 'idx': 16 },
  'kennen': { 'championName': '凱能', 'championKey': 'kennen', 'idx': 58 },
  'kaisa': { 'championName': '凱莎', 'championKey': 'kaisa', 'idx': 50 },
  'xayah': { 'championName': '剎雅', 'championKey': 'xayah', 'idx': 143 },
  'gangplank': { 'championName': '剛普朗克', 'championKey': 'gangplank', 'idx': 33 },
  'galio': { 'championName': '加里歐', 'championKey': 'galio', 'idx': 32 },
  'nunu': { 'championName': '努努和威朗普', 'championKey': 'nunu', 'idx': 85 },
  'zed': { 'championName': '劫', 'championKey': 'zed', 'idx': 151 },
  'leblanc': { 'championName': '勒布朗', 'championKey': 'leblanc', 'idx': 63 },
  'khazix': { 'championName': '卡力斯', 'championKey': 'khazix', 'idx': 59 },
  'karthus': { 'championName': '卡爾瑟斯', 'championKey': 'karthus', 'idx': 53 },
  'katarina': { 'championName': '卡特蓮娜', 'championKey': 'katarina', 'idx': 55 },
  'karma': { 'championName': '卡瑪', 'championKey': 'karma', 'idx': 52 },
  'cassiopeia': { 'championName': '卡莎碧雅', 'championKey': 'cassiopeia', 'idx': 18 },
  'kassadin': { 'championName': '卡薩丁', 'championKey': 'kassadin', 'idx': 54 },
  'camille': { 'championName': '卡蜜兒', 'championKey': 'camille', 'idx': 17 },
  'aatrox': { 'championName': '厄薩斯', 'championKey': 'aatrox', 'idx': 0 },
  'gragas': { 'championName': '古拉格斯', 'championKey': 'gragas', 'idx': 36 },
  'skarner': { 'championName': '史加納', 'championKey': 'skarner', 'idx': 114 },
  'sejuani': { 'championName': '史瓦妮', 'championKey': 'sejuani', 'idx': 104 },
  'jinx': { 'championName': '吉茵珂絲', 'championKey': 'jinx', 'idx': 49 },
  'gnar': { 'championName': '吶兒', 'championKey': 'gnar', 'idx': 35 },
  'jarvaniv': { 'championName': '嘉文四世', 'championKey': 'jarvaniv', 'idx': 45 },
  'twitch': { 'championName': '圖奇', 'championKey': 'twitch', 'idx': 130 },
  'akshan': { 'championName': '埃可尚', 'championKey': 'akshan', 'idx': 3 },
  'ivern': { 'championName': '埃爾文', 'championKey': 'ivern', 'idx': 43 },
  'taliyah': { 'championName': '塔莉雅', 'championKey': 'taliyah', 'idx': 121 },
  'taric': { 'championName': '塔里克', 'championKey': 'taric', 'idx': 123 },
  'talon': { 'championName': '塔隆', 'championKey': 'talon', 'idx': 122 },
  'malphite': { 'championName': '墨菲特', 'championKey': 'malphite', 'idx': 71 },
  'nocturne': { 'championName': '夜曲', 'championKey': 'nocturne', 'idx': 84 },
  'nidalee': { 'championName': '奈德麗', 'championKey': 'nidalee', 'idx': 83 },
  'orianna': { 'championName': '奧莉安娜', 'championKey': 'orianna', 'idx': 87 },
  'missfortune': { 'championName': '好運姐', 'championKey': 'missfortune', 'idx': 75 },
  'neeko': { 'championName': '妮可', 'championKey': 'neeko', 'idx': 82 },
  'senna': { 'championName': '姍娜', 'championKey': 'senna', 'idx': 105 },
  'qiyana': { 'championName': '姬亞娜', 'championKey': 'qiyana', 'idx': 92 },
  'velkoz': { 'championName': '威寇茲', 'championKey': 'velkoz', 'idx': 136 },
  'nami': { 'championName': '娜米', 'championKey': 'nami', 'idx': 79 },
  'annie': { 'championName': '安妮', 'championKey': 'annie', 'idx': 7 },
  'kogmaw': { 'championName': '寇格魔', 'championKey': 'kogmaw', 'idx': 62 },
  'tristana': { 'championName': '崔絲塔娜', 'championKey': 'tristana', 'idx': 126 },
  'bard': { 'championName': '巴德', 'championKey': 'bard', 'idx': 12 },
  'brand': { 'championName': '布蘭德', 'championKey': 'brand', 'idx': 14 },
  'braum': { 'championName': '布郎姆', 'championKey': 'braum', 'idx': 15 },
  'blitzcrank': { 'championName': '布里茨', 'championKey': 'blitzcrank', 'idx': 13 },
  'ziggs': { 'championName': '希格斯', 'championKey': 'ziggs', 'idx': 152 },
  'shyvana': { 'championName': '希瓦娜', 'championKey': 'shyvana', 'idx': 110 },
  'sivir': { 'championName': '希維爾', 'championKey': 'sivir', 'idx': 113 },
  'corki': { 'championName': '庫奇', 'championKey': 'corki', 'idx': 20 },
  'volibear': { 'championName': '弗力貝爾', 'championKey': 'volibear', 'idx': 141 },
  'vladimir': { 'championName': '弗拉迪米爾', 'championKey': 'vladimir', 'idx': 140 },
  'monkeyking': { 'championName': '悟空', 'championKey': 'monkeyking', 'idx': 76 },
  'yuumi': { 'championName': '悠咪', 'championKey': 'yuumi', 'idx': 149 },
  'shen': { 'championName': '慎', 'championKey': 'shen', 'idx': 109 },
  'kayn': { 'championName': '慨影', 'championKey': 'kayn', 'idx': 57 },
  'lux': { 'championName': '拉克絲', 'championKey': 'lux', 'idx': 70 },
  'rammus': { 'championName': '拉姆斯', 'championKey': 'rammus', 'idx': 95 },
  'teemo': { 'championName': '提摩', 'championKey': 'teemo', 'idx': 124 },
  'swain': { 'championName': '斯溫', 'championKey': 'swain', 'idx': 117 },
  'masteryi': { 'championName': '易大師', 'championKey': 'masteryi', 'idx': 74 },
  'syndra': { 'championName': '星朵拉', 'championKey': 'syndra', 'idx': 119 },
  'zac': { 'championName': '札克', 'championKey': 'zac', 'idx': 150 },
  'leesin': { 'championName': '李星', 'championKey': 'leesin', 'idx': 64 },
  'jayce': { 'championName': '杰西', 'championKey': 'jayce', 'idx': 47 },
  'zyra': { 'championName': '枷蘿', 'championKey': 'zyra', 'idx': 155 },
  'zoe': { 'championName': '柔依', 'championKey': 'zoe', 'idx': 154 },
  'zilean': { 'championName': '極靈', 'championKey': 'zilean', 'idx': 153 },
  'olaf': { 'championName': '歐拉夫', 'championKey': 'olaf', 'idx': 86 },
  'vayne': { 'championName': '汎', 'championKey': 'vayne', 'idx': 134 },
  'warwick': { 'championName': '沃維克', 'championKey': 'warwick', 'idx': 142 },
  'varus': { 'championName': '法洛士', 'championKey': 'varus', 'idx': 133 },
  'poppy': { 'championName': '波比', 'championKey': 'poppy', 'idx': 90 },
  'tryndamere': { 'championName': '泰達米爾', 'championKey': 'tryndamere', 'idx': 128 },
  'pyke': { 'championName': '派克', 'championKey': 'pyke', 'idx': 91 },
  'heimerdinger': { 'championName': '漢默丁格', 'championKey': 'heimerdinger', 'idx': 40 },
  'pantheon': { 'championName': '潘森', 'championKey': 'pantheon', 'idx': 89 },
  'urgot': { 'championName': '烏爾加特', 'championKey': 'urgot', 'idx': 132 },
  'udyr': { 'championName': '烏迪爾', 'championKey': 'udyr', 'idx': 131 },
  'samira': { 'championName': '煞蜜拉', 'championKey': 'samira', 'idx': 103 },
  'jhin': { 'championName': '燼', 'championKey': 'jhin', 'idx': 48 },
  'trundle': { 'championName': '特朗德', 'championKey': 'trundle', 'idx': 127 },
  'yone': { 'championName': '犽凝', 'championKey': 'yone', 'idx': 147 },
  'yasuo': { 'championName': '犽宿', 'championKey': 'yasuo', 'idx': 146 },
  'janna': { 'championName': '珍娜', 'championKey': 'janna', 'idx': 44 },
  'seraphine': { 'championName': '瑟菈紛', 'championKey': 'seraphine', 'idx': 106 },
  'thresh': { 'championName': '瑟雷西', 'championKey': 'thresh', 'idx': 125 },
  'chogath': { 'championName': '科加斯', 'championKey': 'chogath', 'idx': 19 },
  'yorick': { 'championName': '約瑞科', 'championKey': 'yorick', 'idx': 148 },
  'nautilus': { 'championName': '納帝魯斯', 'championKey': 'nautilus', 'idx': 81 },
  'nasus': { 'championName': '納瑟斯', 'championKey': 'nasus', 'idx': 80 },
  'sona': { 'championName': '索娜', 'championKey': 'sona', 'idx': 115 },
  'soraka': { 'championName': '索拉卡', 'championKey': 'soraka', 'idx': 116 },
  'viktor': { 'championName': '維克特', 'championKey': 'viktor', 'idx': 139 },
  'viego': { 'championName': '維爾戈', 'championKey': 'viego', 'idx': 138 },
  'veigar': { 'championName': '維迦', 'championKey': 'veigar', 'idx': 135 },
  'aurelionsol': { 'championName': '翱銳龍獸', 'championKey': 'aurelionsol', 'idx': 10 },
  'ekko': { 'championName': '艾克', 'championKey': 'ekko', 'idx': 25 },
  'anivia': { 'championName': '艾妮維亞', 'championKey': 'anivia', 'idx': 6 },
  'ashe': { 'championName': '艾希', 'championKey': 'ashe', 'idx': 9 },
  'maokai': { 'championName': '茂凱', 'championKey': 'maokai', 'idx': 73 },
  'lillia': { 'championName': '莉莉亞', 'championKey': 'lillia', 'idx': 66 },
  'fiora': { 'championName': '菲歐拉', 'championKey': 'fiora', 'idx': 30 },
  'vi': { 'championName': '菲艾', 'championKey': 'vi', 'idx': 137 },
  'graves': { 'championName': '葛雷夫', 'championKey': 'graves', 'idx': 37 },
  'quinn': { 'championName': '葵恩', 'championKey': 'quinn', 'idx': 93 },
  'drmundo': { 'championName': '蒙多醫生', 'championKey': 'drmundo', 'idx': 24 },
  'garen': { 'championName': '蓋倫', 'championKey': 'garen', 'idx': 34 },
  'shaco': { 'championName': '薩科', 'championKey': 'shaco', 'idx': 108 },
  'rumble': { 'championName': '藍寶', 'championKey': 'rumble', 'idx': 101 },
  'tahmkench': { 'championName': '貪啃奇', 'championKey': 'tahmkench', 'idx': 120 },
  'fiddlesticks': { 'championName': '費德提克', 'championKey': 'fiddlesticks', 'idx': 29 },
  'jax': { 'championName': '賈克斯', 'championKey': 'jax', 'idx': 46 },
  'sylas': { 'championName': '賽勒斯', 'championKey': 'sylas', 'idx': 118 },
  'sion': { 'championName': '賽恩', 'championKey': 'sion', 'idx': 112 },
  'sett': { 'championName': '賽特', 'championKey': 'sett', 'idx': 107 },
  'hecarim': { 'championName': '赫克林', 'championKey': 'hecarim', 'idx': 39 },
  'xinzhao': { 'championName': '趙信', 'championKey': 'xinzhao', 'idx': 145 },
  'lucian': { 'championName': '路西恩', 'championKey': 'lucian', 'idx': 68 },
  'singed': { 'championName': '辛吉德', 'championKey': 'singed', 'idx': 111 },
  'twistedfate': { 'championName': '逆命', 'championKey': 'twistedfate', 'idx': 129 },
  'draven': { 'championName': '達瑞文', 'championKey': 'draven', 'idx': 23 },
  'darius': { 'championName': '達瑞斯', 'championKey': 'darius', 'idx': 21 },
  'ornn': { 'championName': '鄂爾', 'championKey': 'ornn', 'idx': 88 },
  'rell': { 'championName': '銳兒', 'championKey': 'rell', 'idx': 97 },
  'rakan': { 'championName': '銳空', 'championKey': 'rakan', 'idx': 94 },
  'kindred': { 'championName': '鏡爪', 'championKey': 'kindred', 'idx': 60 },
  'gwen': { 'championName': '關', 'championKey': 'gwen', 'idx': 38 },
  'akali': { 'championName': '阿卡莉', 'championKey': 'akali', 'idx': 2 },
  'amumu': { 'championName': '阿姆姆', 'championKey': 'amumu', 'idx': 5 },
  'ahri': { 'championName': '阿璃', 'championKey': 'ahri', 'idx': 1 },
  'azir': { 'championName': '阿祈爾', 'championKey': 'azir', 'idx': 11 },
  'renekton': { 'championName': '雷尼克頓', 'championKey': 'renekton', 'idx': 98 },
  'leona': { 'championName': '雷歐娜', 'championKey': 'leona', 'idx': 65 },
  'riven': { 'championName': '雷玟', 'championKey': 'riven', 'idx': 100 },
  'reksai': { 'championName': '雷珂煞', 'championKey': 'reksai', 'idx': 96 },
  'ryze': { 'championName': '雷茲', 'championKey': 'ryze', 'idx': 102 },
  'rengar': { 'championName': '雷葛爾', 'championKey': 'rengar', 'idx': 99 },
  'lulu': { 'championName': '露璐', 'championKey': 'lulu', 'idx': 69 },
  'fizz': { 'championName': '飛斯', 'championKey': 'fizz', 'idx': 31 },
  'malzahar': { 'championName': '馬爾札哈', 'championKey': 'malzahar', 'idx': 72 },
  'morgana': { 'championName': '魔甘娜', 'championKey': 'morgana', 'idx': 78 },
  'mordekaiser': { 'championName': '魔鬥凱薩', 'championKey': 'mordekaiser', 'idx': 77 },
  'lissandra': { 'championName': '麗珊卓', 'championKey': 'lissandra', 'idx': 67 },
  'diana': { 'championName': '黛安娜', 'championKey': 'diana', 'idx': 22 },
  'xerath': { 'championName': '齊勒斯', 'championKey': 'xerath', 'idx': 144 },
};

const champCn2En = {
  '亞歷斯塔': 'alistar',
  '亞菲利歐': 'aphelios',
  '伊澤瑞爾': 'ezreal',
  '伊瑞莉雅': 'irelia',
  '伊羅旖': 'illaoi',
  '伊芙琳': 'evelynn',
  '伊莉絲': 'elise',
  '克雷德': 'kled',
  '克黎思妲': 'kalista',
  '凱爾': 'kayle',
  '凱特琳': 'caitlyn',
  '凱能': 'kennen',
  '凱莎': 'kaisa',
  '剎雅': 'xayah',
  '剛普朗克': 'gangplank',
  '加里歐': 'galio',
  '努努和威朗普': 'nunu',
  '劫': 'zed',
  '勒布朗': 'leblanc',
  '卡力斯': 'khazix',
  '卡爾瑟斯': 'karthus',
  '卡特蓮娜': 'katarina',
  '卡瑪': 'karma',
  '卡莎碧雅': 'cassiopeia',
  '卡薩丁': 'kassadin',
  '卡蜜兒': 'camille',
  '厄薩斯': 'aatrox',
  '古拉格斯': 'gragas',
  '史瓦妮': 'sejuani',
  '史加納': 'skarner',
  '吉茵珂絲': 'jinx',
  '吶兒': 'gnar',
  '嘉文四世': 'jarvaniv',
  '圖奇': 'twitch',
  '埃可尚': 'akshan',
  '埃爾文': 'ivern',
  '塔莉雅': 'taliyah',
  '塔里克': 'taric',
  '塔隆': 'talon',
  '墨菲特': 'malphite',
  '夜曲': 'nocturne',
  '奈德麗': 'nidalee',
  '奧莉安娜': 'orianna',
  '好運姐': 'missfortune',
  '妮可': 'neeko',
  '姍娜': 'senna',
  '姬亞娜': 'qiyana',
  '威寇茲': 'velkoz',
  '娜米': 'nami',
  '安妮': 'annie',
  '寇格魔': 'kogmaw',
  '崔絲塔娜': 'tristana',
  '巴德': 'bard',
  '布蘭德': 'brand',
  '布郎姆': 'braum',
  '布里茨': 'blitzcrank',
  '希格斯': 'ziggs',
  '希瓦娜': 'shyvana',
  '希維爾': 'sivir',
  '庫奇': 'corki',
  '弗力貝爾': 'volibear',
  '弗拉迪米爾': 'vladimir',
  '悟空': 'monkeyking',
  '悠咪': 'yuumi',
  '慎': 'shen',
  '慨影': 'kayn',
  '拉克絲': 'lux',
  '拉姆斯': 'rammus',
  '提摩': 'teemo',
  '斯溫': 'swain',
  '易大師': 'masteryi',
  '星朵拉': 'syndra',
  '札克': 'zac',
  '李星': 'leesin',
  '杰西': 'jayce',
  '枷蘿': 'zyra',
  '柔依': 'zoe',
  '極靈': 'zilean',
  '歐拉夫': 'olaf',
  '汎': 'vayne',
  '沃維克': 'warwick',
  '法洛士': 'varus',
  '波比': 'poppy',
  '泰達米爾': 'tryndamere',
  '派克': 'pyke',
  '漢默丁格': 'heimerdinger',
  '潘森': 'pantheon',
  '烏爾加特': 'urgot',
  '烏迪爾': 'udyr',
  '煞蜜拉': 'samira',
  '燼': 'jhin',
  '特朗德': 'trundle',
  '犽凝': 'yone',
  '犽宿': 'yasuo',
  '珍娜': 'janna',
  '瑟菈紛': 'seraphine',
  '瑟雷西': 'thresh',
  '約瑞科': 'yorick',
  '納帝魯斯': 'nautilus',
  '納瑟斯': 'nasus',
  '索娜': 'sona',
  '索拉卡': 'soraka',
  '維克特': 'viktor',
  '維爾戈': 'viego',
  '維迦': 'veigar',
  '翱銳龍獸': 'aurelionsol',
  '艾克': 'ekko',
  '艾妮維亞': 'anivia',
  '艾希': 'ashe',
  '茂凱': 'maokai',
  '莉莉亞': 'lillia',
  '菲歐拉': 'fiora',
  '菲艾': 'vi',
  '葛雷夫': 'graves',
  '葵恩': 'quinn',
  '蒙多醫生': 'drmundo',
  '蓋倫': 'garen',
  '薩科': 'shaco',
  '藍寶': 'rumble',
  '貪啃奇': 'tahmkench',
  '費德提克': 'fiddlesticks',
  '賈克斯': 'jax',
  '賽勒斯': 'sylas',
  '賽恩': 'sion',
  '賽特': 'sett',
  '赫克林': 'hecarim',
  '趙信': 'xinzhao',
  '路西恩': 'lucian',
  '辛吉德': 'singed',
  '逆命': 'twistedfate',
  '達瑞文': 'draven',
  '達瑞斯': 'darius',
  '鄂爾': 'ornn',
  '銳兒': 'rell',
  '銳空': 'rakan',
  '鏡爪': 'kindred',
  '關': 'gwen',
  '阿卡莉': 'akali',
  '阿姆姆': 'amumu',
  '阿璃': 'ahri',
  '阿祈爾': 'azir',
  '雷尼克頓': 'renekton',
  '雷歐娜': 'leona',
  '雷玟': 'riven',
  '雷珂煞': 'reksai',
  '雷茲': 'ryze',
  '雷葛爾': 'rengar',
  '露璐': 'lulu',
  '飛斯': 'fizz',
  '馬爾札哈': 'malzahar',
  '魔甘娜': 'morgana',
  '魔鬥凱薩': 'mordekaiser',
  '麗珊卓': 'lissandra',
  '黛安娜': 'diana',
  '齊勒斯': 'xerath',
  '科加斯': 'chogath',
};

export { champTable, champCn2En };
