/* eslint-disable */
const promoteList = [
  'aatrox',
  'anivia',
  'ashe',
  'corki',
  'ezreal', 'ezreal',
  'graves', 'graves',
  'irelia', 'irelia', 'irelia', 'irelia', 'irelia',
  'jarvaniv',
  'jinx', 'jinx',
  'kaisa', 'kaisa', 'kaisa',
  'kassadin',
  'katarina',
  'kayle',
  'khazix', 'khazix',
  'kogmaw', 'kogmaw',
  'lillia', 'lillia', 'lillia',
  'lucian', 'lucian',
  'lux',
  'nami', 'nami', 'nami',
  'neeko', 'neeko', 'neeko',
  'nidalee', 'nidalee', 'nidalee',
  'orianna', 'orianna', 'orianna',
  'poppy', 'poppy', 'poppy',
  'rakan', 'rakan',
  'senna', 'senna', 'senna',
  'sett', 'sett', 'sett',
  'sivir',
  'soraka', 'soraka', 'soraka',
  'syndra', 'syndra', 'syndra',
  'tristana',
  'vayne', 'vayne', 'vayne',
  'viego',
  'viktor', 'viktor', 'viktor',
  'xayah',
  'yuumi', 'yuumi', 'yuumi',
  'ziggs',
  'zilean', 'zilean', 'zilean',
];

export default promoteList;
